-- Deploy underground:004-SCAN to pg

DO $$
BEGIN
    CREATE TABLE IF NOT EXISTS CIRCLE.SERIES (
        id BIGSERIAL PRIMARY KEY,
        time_l integer,
        time_utc timestamp with time zone,
        company_id int REFERENCES CIRCLE.COMPANY(id),
        resolution circle.resolution_enum,
        o DOUBLE PRECISION,
        h DOUBLE PRECISION,
        l DOUBLE PRECISION,
        c DOUBLE PRECISION,
        v DOUBLE PRECISION,
        vs DOUBLE PRECISION,
        o_ha DOUBLE PRECISION,
        h_ha DOUBLE PRECISION,
        l_ha DOUBLE PRECISION,
        c_ha DOUBLE PRECISION,
        sma_5 DOUBLE PRECISION,
        sma_10 DOUBLE PRECISION,
        sma_20 DOUBLE PRECISION,
        sma_50 DOUBLE PRECISION,
        sma_100 DOUBLE PRECISION,
        sma_200 DOUBLE PRECISION,
        ema_20 DOUBLE PRECISION,
        ema_25 DOUBLE PRECISION,
        ema_30 DOUBLE PRECISION,
        ema_35 DOUBLE PRECISION,
        ema_40 DOUBLE PRECISION,
        ema_45 DOUBLE PRECISION,
        ema_50 DOUBLE PRECISION,
        ema_55 DOUBLE PRECISION,
        ema_std DOUBLE PRECISION,
        vwap DOUBLE PRECISION,
        rvol DOUBLE PRECISION,
        tp DOUBLE PRECISION,
        pv DOUBLE PRECISION,
        pvs DOUBLE PRECISION,
        pv_buy DOUBLE PRECISION,
        pv_sell DOUBLE PRECISION,
        pv_buy_pct DOUBLE PRECISION,
        pv_color varchar(20),
        pv_mm int,
        vwap_mm int,
        ema_mm int,
        h_s DOUBLE PRECISION,
        l_s DOUBLE PRECISION,
        h_p DOUBLE PRECISION,
        l_p DOUBLE PRECISION
    );
END $$;
